name: Code Quality Check

on:
  workflow_call:
    inputs:
      template_path:
        required: true
        type: string
        description: 'Path to the CloudFormation template file'

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  validate-and-scan:
    name: Validate and Scan Template
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      SAM_CLI_TELEMETRY: 0
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up SAM CLI
        uses: aws-actions/setup-sam@c71dd89d980e49367c70391e8ada4353f52f2800 # v2
        with:
          use-installer: true
      - name: SAM Validate
        run: sam validate --lint -t ${{ inputs.template_path }}
      - name: Run Checkov on template
        uses: bridgecrewio/checkov-action@5051a5cfc7e4c71d95199f81ffafbb490c7e6213
        with:
          file: ${{ inputs.template_path }}
          quiet: true
      - name: Run Checkov on workflows
        uses: bridgecrewio/checkov-action@5051a5cfc7e4c71d95199f81ffafbb490c7e6213
        with:
          directory: .github/workflows
          quiet: true
          skip_check: CKV2_GHA_1
